### ISSUE TITLE
Multiple retries for failed GET requests to discourse to fetch topics

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-message-service#27]
We are observing multiple log entries for each failing discourse call to fetch a particular topic.

<pre>
{"name":"tc-message-service-prod","hostname":"#####","pid":33,"requestId":"50####-43ac-#####-58b355043aa4","level":50,"msg":"Discourse call failed:  { config: { url: 'http://####.#####.com/t/####.json?include_raw=1' },\n  response: \n   { status: 403,\n     data: 'You are not permitted to view the requested resource.' } }","time":"2017-12-13T10:50:59.853Z","v":0}
</pre>

This log is repeated multiple times which seem to overload discourse and cause discourse to rate limit our message api which in turn might be the cause of returning partial or empty set of topics for certain projects.

fyi @gondzo @mtwomey

**Comment by vikasrohit** [comment]
@gondzo Can you please update this issue with your observation and [fix](https://github.com/topcoder-platform/tc-message-service/commit/95805757e1034cae3149fe60c3356a2c82a193ee) that you committed yesterday for this?

**Comment by gondzo** [comment]
Before the fix we were adding multiple request interceptors to axios when calling discourse, so the logs were cluttered with a lot of duplicate and misleading info. 
This is now fixed and we should get a single log for each call to discourse
