### ISSUE TITLE
Reduce number of calls

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-message-service#28]
We are observing too many calls being made to list topics for a project. This issue is to track all such instances where we can reduce the number of calls. To start with here are couple:

- [x] we are making extra db call to fetch dbTopic in https://github.com/topcoder-platform/tc-message-service/blob/dev/app/services/adapter.js#L77 we already have dbTopic fetched in list route https://github.com/topcoder-platform/tc-message-service/blob/dev/app/routes/topics/list.js#L56
- [x] For Managers/Admins we can fetch the topics with discourse's system user in first go without first making extra calls with request user's authorization. https://github.com/topcoder-platform/tc-message-service/blob/dev/app/routes/topics/util.js#L25

fyi @gondzo @mtwomey

**Comment by gondzo** [comment]
1. Agree on the extra db call
2. I guess we could always fetch from discourse as system user and filter on our side ?

**Comment by vikasrohit** [comment]
> I guess we could always fetch from discourse as system user and filter on our side ?

Even maintaining the discourse's security, we can call with system user only when calling user has admin roles, that way we don't have to make `n` number of calls before knowing that user does not have access to the topic.

**Comment by vikasrohit** [comment]
Both optimizations are done.
