### ISSUE TITLE
No need to pass postId in topic update

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-message-service#52]
When updating a topic we require the user to send postId as well. This should be removed and we should always update the first post in the topic.

**Comment by vikasrohit** [comment]
I think we don't need to implement this feature, as we are inclining towards keeping the body of the topic as separate post and don't want to abstract that from the caller. Caller should make explicit calls for the post update when update to the body of the topic is required. We are leaving it to the caller to decide whether to abstract the topic's body from the user or not.

fyi @gondzo
