### ISSUE TITLE
Body post of a topic should not be deletable from posts endpoint.

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-message-service#54]
First post in a topic should not be deleted through posts endpoint. Only when deleting a topic should we delete both topic and first post.

**Comment by vikasrohit** [comment]
I think we don't need to implement this feature, as we are inclining towards keeping the body of the topic as separate post and don't want to abstract that from the caller. Caller should make explicit calls for the post update when update to the body of the topic is required. We are leaving it to the caller to decide whether to abstract the topic's body from the user or not.

fyi @gondzo
