### ISSUE TITLE
Return 200 to sendgrid in case of failure

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-message-service#55]
Validate that even if the message api is down, sendgrid webhook returns 200 to sendgrid so that it does not retry. If retry is needed we should be doing that in our code, may be a separate app or scheduler.

@vikasrohit if the message api is down, then so is the webhook - there is no endpoint to return the success code?

**Comment by vikasrohit** [comment]
My bad @gondzo. Closing the issue.
