### ISSUE TITLE
Remove specifying reference as PROJECT in attachments endpoint

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-message-service#59]
Remove specifying reference as PROJECT in attachments endpoint

@vikasrohit shouldn't post attachments have the same permissions as posts/topics, ie PROJECT level permissions?

**Comment by vikasrohit** [comment]
Yes @gondzo , they should. Sorry I was not clear in my description. What I mean is that, right now it hard codes the reference check to be PROJECT while we can determine that from the `topicId` in the path param and fetching the topic record from the database.
Let me know if it is still unclear.
