### ISSUE TITLE
Access condition using evaluate function

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-message-service#91]
From @vikasrohit:

If you notice the access control for message service here (https://github.com/appirio-tech/tc-message-service/blob/dev/app/services/helper.js#L215), we actually call a project service endpoint and parse the response to check if the calling user is part of the project team. We have done this to make message api independent of project service and I think we are successful in doing that except this parsing logic where message api has to be aware of the project service endpoint and its response structure. Also, we have similar use case for timeline/milestone endpoints where right now we have very tightly coupled logic, via middlewares, to determine access to a timeline or its milestones.

Now my idea is to use our expression evaluator for this access control as well. What if we can add one more field, say `access_condition`, here (https://github.com/appirio-tech/tc-message-service/blob/dev/app/models/referenceLookups.js) which would contain the expression similar to what we have in our form templates. This way we can keep it completely generic and can still control the access of the entities from calling application.

**Comment by maxceem** [comment]
@vikasrohit I have a couple of questions to discuss regarding this issue.

1. Currently, we always call two functions together:
    - `callReferenceEndpoint()`
    - `userHasAccessToEntity()`

    First one retrieves the referenced object (project) and the second one checks permissions using that object. Also, that object is not used by any other code.
    I think we can combine these two functions together and call only `userHasAccessToEntity` which should retrieve the referenced object (it may call `callReferenceEndpoint()` internally) and check permissions.

    As we are going to keep message service decoupled no other code should use the refenreced object.

2. As per suggestion, we can add `access_condition` property to the `ReferenceLookups`. That would work, but it would repeat the same `access_condition` expression for all rows which have the same `reference` field (for all rows at the moment). To remove this duplication we should introduce some new model which would keep `access_condition` per each `reference`. It would be more work, so probably it doesn't have sense to go this way now and we can keep it in the `ReferenceLookups` model. What do you think?

**Comment by vikasrohit** [comment]
1. I think initially these two methods were in single method. We refactored it for better readability and to have code pertaining to the parsing of the reference endpoint in a separate place so that we know that this is the only place we need to modify for making the message API completely decoupled with connect. And I think two separate methods gives us better chance to test the logic because main logic to test here is `userHasAccessToEntity`. `callReferenceEndpoint` is just about calling the endpoint. Still, I am okay with any way as long as we are able to test the logic of checking access based on reference endpoint response.

2. `reference` field in primary key, so we won't have multiple records containing the same `reference`.

**Comment by maxceem** [comment]
1. yeah understand. I think we can still have two methods separate for testing, but also have a third one, which will combine these two, and which one we will actually use everywhere. The reason for that is that currently `userHasAccessToEntity` is the sync method which returns results synchronously. Though with a new logic the method would have to call DB to retrieve `access_condition` for the `reference`. So if we use them separately we would have to add one more level of callbacks in the code everywhere.

   Note, we don't have unit tests for `userHasAccessToEntity` logic at the moment.

2. got it, was mislead.

**Comment by maxceem** [comment]
@vikasrohit I think you are right, that we cannot combine these two methods. Here is the reason:

I think the logic in these lines has an issue https://github.com/appirio-tech/tc-message-service/blob/dev/app/routes/topics/create.js#L46-L52:
```js
return helper.callReferenceEndpoint(req.authToken, req.id, params.reference, params.referenceId)
      .then((hasAccessResp) => {
        const hasAccess = helper.userHasAccessToEntity(userId, hasAccessResp, params.reference);
        if (!hasAccess && !helper.isAdmin(req)) {
          logger.info('should return after here');
          throw new errors.HttpStatusError(403, 'User doesn\'t have access to the entity');
        }
```

If the project doesn't exist, the method `callReferenceEndpoint` would return `[false, null, error]`. Though we don't process the `error` anywhere. `userHasAccessToEntity` will return `hasAccess = false`. But if we use admin user, then we will still bypass this condition:
```js
 if (!hasAccess && !helper.isAdmin(req)) {
```

Thus admins can create messages for the project or other entities which don't exist.

To be able to fix such issues we should keep methods `callReferenceEndpoint` and `userHasAccessToEntity` separate, but also additionally check for `error` after `callReferenceEndpoint` method and return an error like `referenced entity doesn't exist` or something like that. And only if the entity exists, we should use method `userHasAccessToEntity` for checking permissions.

What do you think?
